### ISSUE TITLE
SUPPORT

### ISSUE THREAD

**Issue by irsouryo** [Justasic/Spigot-SSHD#2]
I do not understand how to configure, there is a video how to configure it?

**Comment by ZachyFoxx** [comment]
What part of the config is confusing? Most of it is commented on what the config nodes do. We don't currently have a video on how to configure it, but we might work on one in the future.

I would be happy to help you with your configuration if you tell me which part of it is difficult to understand so we can also make it easier for everyone else to understand it aswell.

**Comment by irsouryo** [comment]
I can’t understand part 4, 5, 6 of the settings, I generated the code, then I created the authorized_keys file, and my nickname, after rebooting, didn’t do anything in the console, but I didn’t understand part 5, 6.

**Comment by Justasic** [comment]
The contents of the file named your ssh username is the contents of puttygen's `Public key for pasting into OpenSSH authorized_keys file`. Effectively this is your public key just named as your username.

For example: If you want to login to the console with `Erensisman09@myminecraftserver.com` then you would create a new file in the authorized_users directory named exactly `Erensisman09` and it would contain the key from puttygen mentioned above. 

This works exactly like setting a key up for SSH on any other system but the difference here is that instead of putting the key inside of the `~/.ssh/authorized_keys` file on linux, you're putting it in a file that is named your login name as the plugin uses the name of that file for your username and the contents of the file for the public key.

Hope that helped clarify some things! 😊

**Comment by irsouryo** [comment]
Thanks!

**Comment by irsouryo** [comment]
Hello, it does not work for me.
Photo as configured:
[File config](https://sun6-19.userapi.com/whXI2c1IPofbL2qi9PV_-bIg-q_QzpP0FZKwoA/7MWrbuga1Ak.jpg)
[File Keys](https://sun6-13.userapi.com/Nfp7Ud5ZNECx1llhwB63U07XHC3BcMaH6htBfQ/IqCjVseoNEQ.jpg)
[The public key](https://sun6-14.userapi.com/k8cFQ1DL2MH4b7EmwJCRSe63ba5bJoErCDyRkQ/iipuupuEyyw.jpg)

**Comment by ZachyFoxx** [comment]
Could you please explain in more detail about how it is not working so I can try to help?

**Comment by irsouryo** [comment]
Well, I don’t know, I went into the PuttyGen program and then generated the RSA code, then I went to the authorized_keys folder, and created the authorized_keys file but nothing works, I decided to make the test file also not work.

**Comment by Justasic** [comment]
According to your images, what you would have to do is login as `authorized_keys@yourminecraftserver.com` in putty. The name of the key file is the username for ssh. The test file would mean you would need to login as `test@yourminecraftserver.com`. You only need to put files named as the username in the `authorized_keys` folder, no file named `authorized_keys` needs to exist like it does with OpenSSH. Hope this helps! 😊

**Comment by irsouryo** [comment]
Okay, but I can’t connect.
[Config Putty](https://sun6-14.userapi.com/XSiK4vAl8BSUuFu9fVpJIInunhbnViqtxYN4qg/xX3FSkwCsfc.jpg)
[Error](https://sun6-14.userapi.com/ZXs1vslD4s5Hh-wsMVrSR0MSKBKD1OMa93z_jQ/d0BruH-5_Fw.jpg)

**Comment by ZachyFoxx** [comment]
You should be logging in as the user defined by the file name in the `authorized_keys` folder.

e.g. `myuser@164.132.203.64`

**Comment by irsouryo** [comment]
I can’t connect, the connection is interrupted.

**Comment by Justasic** [comment]
You need to connect on port 1025, did you allow that on your ~config~ firewall?

**Comment by irsouryo** [comment]
Yes, I connect to this port, but I did not understand on which computer I need to configure Firewall?
